In [13]:
import sys
from pathlib import Path

import numpy as np
import optuna
import pandas as pd
from sklearn.base import clone
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report,
    make_scorer,
    f1_score,
)
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    LabelEncoder,
    PolynomialFeatures,
    StandardScaler,
)

In [2]:
REPO_PATH = Path('/content/course_paper')

!git clone --depth 1 --filter=blob:none --sparse https://github.com/incRED1bl/course_paper.git {REPO_PATH}
!git -C {REPO_PATH} sparse-checkout set colab/data/respiratory_features.csv

sys.path.insert(0, str(REPO_PATH))

!cp {REPO_PATH}/colab/data/respiratory_features.csv ../../data/respiratory_features.csv

Cloning into '/content/course_paper'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 7 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (8/8), done.
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 32.07 KiB | 2.67 MiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (1/1), 44.47 KiB | 3.71 MiB/s, done.
cp: cannot create regular file '../../data/respiratory_features.csv': No such file or directory

In [3]:
df = pd.read_csv('/content/course_paper/colab/data/respiratory_features.csv')
df.head()

,filename,patient_id,low_freq_energy,mid_freq_energy,high_freq_energy,whistle_strength,spectral_centroid,peak_frequency,entropy,complexity,diagnosis
0,101_1b1_Al_sc_Meditron.wav,101,0.638772,0.061506,0.299722,0.027502,2317.564152,21.533203,0.815790,0.146400,Unknown
1,101_1b1_Pr_sc_Meditron.wav,101,0.853642,0.026700,0.119657,0.029523,934.166042,0.000000,0.884253,0.097903,Unknown
2,102_1b1_Ar_sc_Meditron.wav,102,0.697796,0.135208,0.166997,0.034458,1253.170052,0.000000,0.898144,0.087052,Healthy
3,103_2b2_Ar_mc_LittC2SE.wav,103,0.658031,0.058343,0.283626,0.027033,2190.655897,0.000000,0.868986,0.110194,Asthma
4,104_1b1_Al_sc_Litt3200.wav,104,0.954556,0.037111,0.008333,0.046673,81.716123,0.000000,0.647283,0.233463,COPD

In [4]:
df = df.drop(columns=['filename', 'patient_id'])
df = df[df['diagnosis'] != 'Unknown']
df.head()

,low_freq_energy,mid_freq_energy,high_freq_energy,whistle_strength,spectral_centroid,peak_frequency,entropy,complexity,diagnosis
2,0.697796,0.135208,0.166997,0.034458,1253.170052,0.0000,0.898144,0.087052,Healthy
3,0.658031,0.058343,0.283626,0.027033,2190.655897,0.0000,0.868986,0.110194,Asthma
4,0.954556,0.037111,0.008333,0.046673,81.716123,0.0000,0.647283,0.233463,COPD
5,0.799876,0.187994,0.012130,0.044284,198.766348,7.8125,0.701699,0.210539,COPD
6,0.885614,0.090175,0.024211,0.015177,211.954439,15.6250,0.637505,0.237087,COPD

In [5]:
def map_diagnosis(x):
    if x == 'Healthy':
        return 'Healthy'
    elif x == 'COPD':
        return 'COPD'
    else:
        return 'Disease'

df['diagnosis'] = df['diagnosis'].apply(map_diagnosis)
df.head()

,low_freq_energy,mid_freq_energy,high_freq_energy,whistle_strength,spectral_centroid,peak_frequency,entropy,complexity,diagnosis
2,0.697796,0.135208,0.166997,0.034458,1253.170052,0.0000,0.898144,0.087052,Healthy
3,0.658031,0.058343,0.283626,0.027033,2190.655897,0.0000,0.868986,0.110194,Disease
4,0.954556,0.037111,0.008333,0.046673,81.716123,0.0000,0.647283,0.233463,COPD
5,0.799876,0.187994,0.012130,0.044284,198.766348,7.8125,0.701699,0.210539,COPD
6,0.885614,0.090175,0.024211,0.015177,211.954439,15.6250,0.637505,0.237087,COPD

In [6]:
X = df.drop(columns=['diagnosis'])
y_raw = df['diagnosis']

In [7]:
le = LabelEncoder()
y = le.fit_transform(y_raw)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [9]:
X_train = X_train.reset_index(drop=True)
X_test  = X_test.reset_index(drop=True)
y_train = np.asarray(y_train)
y_test  = np.asarray(y_test)

In [15]:
!pip install optuna
# !rm respiratory_optuna.db
scorer = make_scorer(f1_score, average='macro')

def objective(trial):
    C = trial.suggest_float("C", 1e-3, 100, log=True)
    tol = trial.suggest_float("tol", 1e-6, 1e-2, log=True)
    max_iter = trial.suggest_int("max_iter", 200, 2000, step=100)

    solver = trial.suggest_categorical("solver", ["lbfgs", "liblinear", "saga"])

    penalty = "l2"
    if solver in ["liblinear", "saga"]:
        penalty = trial.suggest_categorical("penalty", ["l1", "l2", "elasticnet"])

    l1_ratio = None
    if penalty == "elasticnet":
        l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)

    class_weight = trial.suggest_categorical("class_weight", [None, "balanced"])

    poly_degree = trial.suggest_int("poly_degree", 1, 2)

    prep = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("poly", PolynomialFeatures(degree=poly_degree, include_bias=False)),
        ("scaler", StandardScaler()),
    ])

    clf = LogisticRegression(
        C=C,
        tol=tol,
        max_iter=max_iter,
        solver=solver,
        penalty=penalty,
        l1_ratio=l1_ratio,
        class_weight=class_weight,
        random_state=42,
        n_jobs=-1
    )

    model = Pipeline([("prep", prep), ("clf", clf)])

    try:
        scores = cross_val_score(
            model,
            X_train,
            y_train,
            cv=StratifiedKFold(n_splits=4, shuffle=True, random_state=42),
            scoring=scorer,
            n_jobs=-1
        )
        return scores.mean()
    except Exception as e:
        print(f"Trial failed: {e}")
        return 0.0


study = optuna.create_study(
    direction="maximize",
    study_name="respiratory_logreg_macrof1",
    storage="sqlite:///respiratory_optuna.db",
    load_if_exists=True
)

study.optimize(
    objective,
    n_trials=60,
    timeout=5400,
    show_progress_bar=True
)

best_result = {
    "best_macro_f1": round(study.best_value, 5),
    **study.best_params
}

print("\nBest macro-F1:", best_result["best_macro_f1"])
print("best_params = {")
for k, v in best_result.items():
    if k == "best_macro_f1":
        continue
    else:
        if isinstance(v, str):
            print(f"    '{k}': '{v}',")
        elif isinstance(v, (int, float)):
            print(f"    '{k}': {v},")
        else:
            print(f"    '{k}': {v!r},")
print("}")

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.7.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

[I 2026-02-21 13:58:54,745] Using an existing study with name 'respiratory_logreg_macrof1' instead of creating a new one.

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-02-21 13:58:55,767] Trial 120 finished with value: 0.536230778983776 and parameters: {'C': 0.33103799503647596, 'tol': 2.2153981507101027e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'l2', 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:58:56,709] Trial 121 finished with value: 0.536230778983776 and parameters: {'C': 0.3404567877765996, 'tol': 2.101794580934273e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'l2', 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:58:57,720] Trial 122 finished with value: 0.5615199678507296 and parameters: {'C': 0.4326789297817827, 'tol': 2.0818345551578406e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'l2', 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:58:59,208] Trial 123 finished with value: 0.5615199678507296 and parameters: {'C': 0.40883497223266996, 'tol': 1.3326385738896042e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'l2', 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:00,199] Trial 124 finished with value: 0.5349809482787293 and parameters: {'C': 0.3768160119536644, 'tol': 1.9707400460970673e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'l2', 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:01,155] Trial 125 finished with value: 0.5148466132304771 and parameters: {'C': 0.4528301679115618, 'tol': 1.1825371082604957e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7125633130264084, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:02,023] Trial 126 finished with value: 0.49995828126889563 and parameters: {'C': 0.34041252182366805, 'tol': 1.3099264579325897e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7794942855341531, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:02,912] Trial 127 finished with value: 0.5037579498764087 and parameters: {'C': 0.360192038581177, 'tol': 1.1359618557382695e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7656655252424514, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:03,787] Trial 128 finished with value: 0.5125544654286184 and parameters: {'C': 0.37628922843279555, 'tol': 1.2722967819537588e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7577619062310278, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:04,656] Trial 129 finished with value: 0.508011055744562 and parameters: {'C': 0.37540127503492543, 'tol': 1.2595557271660305e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7668952894311173, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:05,518] Trial 130 finished with value: 0.5280616767773889 and parameters: {'C': 0.4128132039865022, 'tol': 1.0210364083606495e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7599707735504168, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:06,386] Trial 131 finished with value: 0.5280616767773889 and parameters: {'C': 0.4175864179374925, 'tol': 1.5863498027417948e-06, 'max_iter': 200, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7618147756462212, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:07,557] Trial 132 finished with value: 0.5303131931258619 and parameters: {'C': 0.43493014032807503, 'tol': 1.6071878359744441e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.7933666593105779, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:08,745] Trial 133 finished with value: 0.5374198218029087 and parameters: {'C': 0.5253471415790048, 'tol': 1.517951065437663e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6106533107492645, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:09,984] Trial 134 finished with value: 0.5391668228463715 and parameters: {'C': 0.9284105567957822, 'tol': 1.586760235470481e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6223585334297184, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:11,513] Trial 135 finished with value: 0.5420438514876844 and parameters: {'C': 0.882489755892083, 'tol': 1.7036729060618858e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.6283732715324988, 'class_weight': None, 'poly_degree': 2}. Best is trial 118 with value: 0.5625944715099295.
[I 2026-02-21 13:59:13,430] Trial 136 finished with value: 0.566214533801708 and parameters: {'C': 1.3710682251176887, 'tol': 1.5765018517898268e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5548450239603939, 'class_weight': None, 'poly_degree': 2}. Best is trial 136 with value: 0.566214533801708.
[I 2026-02-21 13:59:14,745] Trial 137 finished with value: 0.543444411711774 and parameters: {'C': 1.0072349322356964, 'tol': 1.8718404767811267e-06, 'max_iter': 300, 'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5837934508722982, 'class_weight': None, 'poly_degree': 2}. Best is trial 136 with value: 0.566214533801708.
[I 2026-02-21 13:59:15,207] Trial 138 finished with value: 0.5968357071050138 and parameters: {'C': 1.3900031539490698, 'tol': 1.872460931921814e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:15,658] Trial 139 finished with value: 0.5968357071050138 and parameters: {'C': 1.502884731583551, 'tol': 1.9090541285402606e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:16,073] Trial 140 finished with value: 0.5968357071050138 and parameters: {'C': 1.4300987639641585, 'tol': 1.8645346115333413e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:16,512] Trial 141 finished with value: 0.5968357071050138 and parameters: {'C': 1.3290978324480465, 'tol': 1.9211661442770894e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:16,934] Trial 142 finished with value: 0.5968357071050138 and parameters: {'C': 1.3289644375760692, 'tol': 1.9261352981241797e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:17,390] Trial 143 finished with value: 0.5968357071050138 and parameters: {'C': 1.4595448367786, 'tol': 1.6922881339289966e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:17,835] Trial 144 finished with value: 0.5968357071050138 and parameters: {'C': 1.4254196260988294, 'tol': 1.8353868189327633e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:18,279] Trial 145 finished with value: 0.5968357071050138 and parameters: {'C': 1.549387060931325, 'tol': 1.7068464183629093e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 138 with value: 0.5968357071050138.
[I 2026-02-21 13:59:18,730] Trial 146 finished with value: 0.6007156882744605 and parameters: {'C': 1.6703360892558885, 'tol': 1.826473609114772e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:19,199] Trial 147 finished with value: 0.5968357071050138 and parameters: {'C': 1.5147821096524603, 'tol': 1.8598090018370052e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:19,618] Trial 148 finished with value: 0.5968357071050138 and parameters: {'C': 1.4421578741149836, 'tol': 2.3607921065127254e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:20,051] Trial 149 finished with value: 0.5968357071050138 and parameters: {'C': 1.5040860518616634, 'tol': 2.4169373193795737e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:20,499] Trial 150 finished with value: 0.5968357071050138 and parameters: {'C': 1.5530283298965968, 'tol': 2.6086847913111903e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:20,918] Trial 151 finished with value: 0.5968357071050138 and parameters: {'C': 1.5274889197029524, 'tol': 2.533521466760656e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:21,330] Trial 152 finished with value: 0.5968357071050138 and parameters: {'C': 1.4961002127258698, 'tol': 2.43863672905117e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:21,762] Trial 153 finished with value: 0.5968357071050138 and parameters: {'C': 1.4035122821069763, 'tol': 2.5584717081704425e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:22,233] Trial 154 finished with value: 0.5970316923296656 and parameters: {'C': 2.068478358554309, 'tol': 2.6290630493633666e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:22,732] Trial 155 finished with value: 0.5970316923296656 and parameters: {'C': 2.105395470265914, 'tol': 2.45269767133328e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:23,210] Trial 156 finished with value: 0.5930020083557626 and parameters: {'C': 2.2834814330333737, 'tol': 1.9039435180240456e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 146 with value: 0.6007156882744605.
[I 2026-02-21 13:59:23,762] Trial 157 finished with value: 0.609692324871778 and parameters: {'C': 3.093310048961375, 'tol': 2.737705721975738e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 157 with value: 0.609692324871778.
[I 2026-02-21 13:59:24,514] Trial 158 finished with value: 0.5970316923296656 and parameters: {'C': 2.038080127977752, 'tol': 1.8157015794551904e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 157 with value: 0.609692324871778.
[I 2026-02-21 13:59:25,403] Trial 159 finished with value: 0.6124250891691039 and parameters: {'C': 3.5117693243662482, 'tol': 1.4212250809657848e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 159 with value: 0.6124250891691039.
[I 2026-02-21 13:59:26,264] Trial 160 finished with value: 0.6225440564735096 and parameters: {'C': 3.3024645457052553, 'tol': 1.3406593880770292e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:26,925] Trial 161 finished with value: 0.6124250891691039 and parameters: {'C': 3.8867984134155975, 'tol': 1.776160291047033e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:27,479] Trial 162 finished with value: 0.6160931000225531 and parameters: {'C': 3.4283491364290577, 'tol': 1.3898711230874265e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:28,073] Trial 163 finished with value: 0.6124250891691039 and parameters: {'C': 3.8145665815352023, 'tol': 1.358171752625112e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:28,570] Trial 164 finished with value: 0.6124250891691039 and parameters: {'C': 4.099217881336604, 'tol': 1.3738630867262317e-06, 'max_iter': 300, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:29,175] Trial 165 finished with value: 0.6124250891691039 and parameters: {'C': 4.18431163505278, 'tol': 1.006582219054985e-06, 'max_iter': 400, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:29,762] Trial 166 finished with value: 0.6124250891691039 and parameters: {'C': 3.6852180247500343, 'tol': 1.0349725569772124e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:30,370] Trial 167 finished with value: 0.6124250891691039 and parameters: {'C': 3.9853980752485216, 'tol': 1.0559430075747252e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:31,004] Trial 168 finished with value: 0.6124250891691039 and parameters: {'C': 3.9993202710960216, 'tol': 1.0335290182953394e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:31,646] Trial 169 finished with value: 0.6124250891691039 and parameters: {'C': 4.307298771246405, 'tol': 1.0134893729684493e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:32,253] Trial 170 finished with value: 0.6124250891691039 and parameters: {'C': 3.946245303866082, 'tol': 1.1212386153054165e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:32,876] Trial 171 finished with value: 0.6124250891691039 and parameters: {'C': 3.9591365246048738, 'tol': 1.0290376507156901e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:33,489] Trial 172 finished with value: 0.6124250891691039 and parameters: {'C': 3.9673234109966597, 'tol': 1.042448872873274e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:34,119] Trial 173 finished with value: 0.6124250891691039 and parameters: {'C': 4.083372975976584, 'tol': 1.011758016982142e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:34,731] Trial 174 finished with value: 0.6124250891691039 and parameters: {'C': 3.8990125665010997, 'tol': 1.0332922445341254e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:35,345] Trial 175 finished with value: 0.6124250891691039 and parameters: {'C': 3.643628058518649, 'tol': 1.021625041245631e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:35,949] Trial 176 finished with value: 0.6124250891691039 and parameters: {'C': 3.8994854239482093, 'tol': 1.115435877821463e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:36,683] Trial 177 finished with value: 0.6124250891691039 and parameters: {'C': 4.271578939066677, 'tol': 1.043539196528137e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:37,775] Trial 178 finished with value: 0.6124250891691039 and parameters: {'C': 6.053890465643078, 'tol': 1.0013962129114423e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.
[I 2026-02-21 13:59:38,626] Trial 179 finished with value: 0.6160931000225531 and parameters: {'C': 3.3548813307615872, 'tol': 1.2647453508418666e-06, 'max_iter': 500, 'solver': 'lbfgs', 'class_weight': None, 'poly_degree': 2}. Best is trial 160 with value: 0.6225440564735096.

Best macro-F1: 0.62254
best_params = {
    'C': 3.3024645457052553,
    'tol': 1.3406593880770292e-06,
    'max_iter': 400,
    'solver': 'lbfgs',
    'class_weight': None,
    'poly_degree': 2,
}

In [16]:
best_params = {
    'C': 3.3024645457052553,
    'tol': 1.3406593880770292e-06,
    'max_iter': 400,
    'solver': 'lbfgs',
    'class_weight': None,
    'poly_degree': 2,
}

In [17]:
best_poly_degree = best_result['poly_degree']

prep = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("poly", PolynomialFeatures(degree=best_poly_degree, include_bias=False)),
    ("scaler", StandardScaler()),
])

In [18]:
best_clf = LogisticRegression(
    C=best_result['C'],
    tol=best_result['tol'],
    max_iter=best_result['max_iter'],
    solver=best_result['solver'],
    penalty=best_result.get('penalty', 'l2'),
    l1_ratio=best_result.get('l1_ratio', None),
    class_weight=best_result.get('class_weight', None),
    random_state=42,
    n_jobs = 1 if best_result['solver'] == 'liblinear' else -1
)

In [19]:
model = Pipeline([
    ("prep", prep),
    ("clf", best_clf)
])

In [20]:
model["prep"].fit_transform(X_train).shape

(734, 44)

In [21]:
model

Pipeline(steps=[('prep',
                 Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                                 ('poly',
                                  PolynomialFeatures(include_bias=False)),
                                 ('scaler', StandardScaler())])),
                ('clf',
                 LogisticRegression(C=3.3024645457052553, max_iter=400,
                                    n_jobs=-1, random_state=42,
                                    tol=1.3406593880770292e-06))])

In [22]:
oof_pred = np.zeros(len(y_train), dtype=np.int64)
fold_acc = []
fold_auc_macro = []
fold_auc_weighted = []

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for fold, (tr_idx, val_idx) in enumerate(cv.split(X_train, y_train), 1):
    print(f"Fold {fold}/5 ... ", end="")

    m = clone(model)
    m.fit(X_train.iloc[tr_idx], y_train[tr_idx])

    proba = m.predict_proba(X_train.iloc[val_idx])
    pred = m.classes_[np.argmax(proba, axis=1)]

    oof_pred[val_idx] = pred

    acc = accuracy_score(y_train[val_idx], pred)
    auc_macro   = roc_auc_score(y_train[val_idx], proba, multi_class="ovr", average="macro")
    auc_weighted = roc_auc_score(y_train[val_idx], proba, multi_class="ovr", average="weighted")

    fold_acc.append(acc)
    fold_auc_macro.append(auc_macro)
    fold_auc_weighted.append(auc_weighted)

    print(f"ACC={acc:.4f} | AUC(macro)={auc_macro:.4f} | AUC(w)={auc_weighted:.4f}")

Fold 1/5 ... ACC=0.9184 | AUC(macro)=0.9719 | AUC(w)=0.9660
Fold 2/5 ... ACC=0.8912 | AUC(macro)=0.9417 | AUC(w)=0.9613
Fold 3/5 ... ACC=0.8707 | AUC(macro)=0.9402 | AUC(w)=0.9633
Fold 4/5 ... ACC=0.8571 | AUC(macro)=0.8842 | AUC(w)=0.9553
Fold 5/5 ... ACC=0.8973 | AUC(macro)=0.9624 | AUC(w)=0.9755

In [23]:
print("\n" + "─"*70)
print("Cross-validation results (5 folds)")
print("─"*70)
print(f"Accuracy mean     : {np.mean(fold_acc):.4f} ± {np.std(fold_acc):.4f}")
print(f"AUC macro mean    : {np.mean(fold_auc_macro):.4f} ± {np.std(fold_auc_macro):.4f}")
print(f"AUC weighted mean : {np.mean(fold_auc_weighted):.4f} ± {np.std(fold_auc_weighted):.4f}")
print("─"*70)

print("\nOOF Classification Report (full training set):")
print(classification_report(
    y_train,
    oof_pred,
    target_names=le.classes_,
    digits=4
))

──────────────────────────────────────────────────────────────────────
Cross-validation results (5 folds)
──────────────────────────────────────────────────────────────────────
Accuracy mean     : 0.8869 ± 0.0213
AUC macro mean    : 0.9401 ± 0.0304
AUC weighted mean : 0.9643 ± 0.0066
──────────────────────────────────────────────────────────────────────

OOF Classification Report (full training set):
              precision    recall  f1-score   support

        COPD     0.9486    0.9606    0.9545       634
     Disease     0.5075    0.4722    0.4892        72
     Healthy     0.3200    0.2857    0.3019        28

    accuracy                         0.8869       734
   macro avg     0.5920    0.5728    0.5819       734
weighted avg     0.8813    0.8869    0.8840       734

In [24]:
model.fit(X_train, y_train)
test_pred = model.predict(X_test)
test_acc = accuracy_score(y_test, test_pred)
print("Test ACC:", test_acc)

Test ACC: 0.8586956521739131